version: '3'

services:
  pg:
    image: "postgres"
    ports:
      - 7200:5432

  redis:
    image: redis:4.0.5-alpine
    ports:
      - 7100:6379



#    hostname: redis
#    networks:
#      - redis-net
#    volumes:
#      - redis-data:/data
#
#networks:
#  redis-net:
#
#volumes:
#  redis-data: