# in order to use this compose file, you need to create a github personal access token,
# and export it in your local environment, so docker-compose can access private tutti-ch repos.
# The token only need to have read access to private repositories, and nothing else.
# Never include your personal token in version control.
#
version: '3'

services:
  pg:
    image: "postgres"
    ports:
      - 8100:5432

  redis:
    image: redis:4.0.5-alpine
    ports:
      - 6379:6379



#    hostname: redis
#    networks:
#      - redis-net
#    volumes:
#      - redis-data:/data
#
#networks:
#  redis-net:
#
#volumes:
#  redis-data: